### ISSUE TITLE
Having console errors when using with two tilesources.

### ISSUE THREAD

**Issue by SamHall** [antonioxdias/OpenSeadragonHTMLelements#12]
I've utilized the OpenSeadragonHTMLelements plugin to display overlays on the canvas - and it works fine.
I want to also have a 2nd dzi toggle option using a method shared here previously.

Both of these demos work, but the 2nd one with the toggle option is throwing errors by the thousands.
I know what the error is saying, but cannot figure out where/how to appease viewer.js. Any help would be appreciated.
Thank you.

Demo with one dzi: https://chattanoogahistory.com/htmloverlaytest.html
Demo with two dzi's spewing errors: https://chattanoogahistory.com/htmloverlaytestTWO.html

It appears to work fine, but I'd rather suppress the errors or fix it.

Errors example:
viewport.js:1217 [Viewport.imageToViewportCoordinates] is not accurate with multi-image; use TiledImage.imageToViewportCoordinates instead.
viewport.js:1259 [Viewport.imageToViewportRectangle] is not accurate with multi-image; use TiledImage.imageToViewportRectangle instead.

**Comment by antonioxdias** [comment]
When consuming multiple sources in OSD any coordinate calculations should be done in relation to the proper tiledImages, as these can be rendered anywhere in the viewer world.
This is precisely what the error message is describing, as the viewer expects the plugin to get those coordinates from a specific TiledImage, instead from the viewport.

In your case, the HTML elements actually work 'fine' because your TiledImages are placed on top of one another, which means the coordinates would be the same.

If all you need is to have the warnings not showing, and you're happy with the current behaviour, you can fork the plugin and refactor any coordinate related calculations from `viewer.viewport` to `viewer.world.getItemAt(0)` .

**Comment by iangilman** [comment]
If we want this plugin to work with multiple images, it should be updated to use viewport coordinates internally instead of image coordinates, since viewport coordinates are consistent across all images. Let me know if you want more info about that!

BTW, I'm not sure I was aware of this plugin when I wrote https://github.com/openseadragon/html-overlay, but they both tackle similar problems in different ways. I wonder if there's a "best of both worlds" that could exist? @antonioxdias are you interested in continuing to evolve this plugin? Have you taken a look at the other one to compare techniques? 

@SamHall you might try the other plugin; I think it should work with multiple images.

**Comment by SamHall** [comment]
Thank you - I'll review it tonight as it may have to replace the existing code.
The page I'm working on has several dozen overlays already built on the first one.
Ultimately - I'll need to go with what works best.

**Comment by SamHall** [comment]
> When consuming multiple sources in OSD any coordinate calculations should be done in relation to the proper tiledImages, as these can be rendered anywhere in the viewer world.
> This is precisely what the error message is describing, as the viewer expects the plugin to get those coordinates from a specific TiledImage, instead from the viewport.
> 
> In your case, the HTML elements actually work 'fine' because your TiledImages are placed on top of one another, which means the coordinates would be the same.
> 
> If all you need is to have the warnings not showing, and you're happy with the current behaviour, you can fork the plugin and refactor any coordinate related calculations from `viewer.viewport` to `viewer.world.getItemAt(0)` .

I am happy with how it's working and really want to stick with it.

I get the gist of what you're saying but am admittedly not very fluent in JavaScript.  Would you provide a full example of such edits? 

```
function repositionElement(e, viewer) {
  const newRect = viewer.viewport.viewportToViewerElementRectangle(
    viewer.viewport.imageToViewportRectangle(e.rect)
  )
  const point = viewer.viewport.getFlip()
    ? flipPoint(
        { x: e.rect.x, y: e.rect.y },
        viewer.viewport.getRotation(),
        viewer.world
          .getItemAt(0)
          .viewportToImageCoordinates(viewer.viewport.getCenter(true))
      )
    : { x: e.rect.x, y: e.rect.y }
  const pos = viewer.viewport.viewportToViewerElementCoordinates(
    viewer.viewport.imageToViewportCoordinates(point.x, point.y)
  )
  e.element.style.left = pos.x - newRect.width / 2 + 'px'
  e.element.style.top = pos.y - newRect.height / 2 + 'px'
  e.element.style.width = newRect.width + 'px'
  e.element.style.height = newRect.height + 'px'
  if ('fontSize' in e) {
    e.element.style.fontSize =
      (e.fontSize * viewer.viewport.getZoom(true)) /
        viewer.viewport.getHomeZoom() +
      'px'
  }
}
```

**Comment by SamHall** [comment]
Here's what I'm working on. Due to the time/effort I've put into it - I really would like to stick with this method.

https://chattanoogahistory.com/ghostsofcameron3#

**Comment by antonioxdias** [comment]
@iangilman You were certainly at some point 😃 as you approved the [PR in the osd-site](https://github.com/openseadragon/site-build/pull/202) adding it, and also have a snippet in your (very helpful!) [recipes catalog](https://codepen.io/iangilman/pen/PyegxP) with the base idea for the plugin.

I actually haven't used OSD for a couple years now, so i'm not really up to date with the latest features and ideas. I do try to solve any issues that pop up here in the plugin repo, and certainly don't mind keep doing it or help elsewhere, whenever i can spare the time.

I'll take a deeper look at the approaches used in [html-overlay](https://github.com/openseadragon/html-overlay), but for now i can already see that at least you could do away with the terrible CSS jitter i encountered when dealing with text, by using transform instead of adjusting font-size. That's pretty neat!

**Comment by antonioxdias** [comment]
@SamHall Can you give a try to [the version in this branch](https://github.com/antonioxdias/OpenSeadragonHTMLelements/tree/chore/use-tiled-image-coordinates) ? I couldn't really set up a proper test environment to test it out, but i think it might solve your issue for now.

**Comment by SamHall** [comment]
@antonioxdias,
Thank you for the quick response.
I tried it out on the page linked below. 
https://chattanoogahistory.com/htmloverlaytestTWO.html

Error occurs at the first hEl.addElement:
```
OpenSeadragonHTMLelements.js:163 Uncaught TypeError: Cannot read property 'imageToViewportRectangle' of undefined
    at repositionElement (OpenSeadragonHTMLelements.js:163)
    at $.hElements.addElement (OpenSeadragonHTMLelements.js:69)
    at htmloverlaytestTWO.html:149
```

**Comment by iangilman** [comment]
@antonioxdias yes, clearly I was aware of it at one time! :D Anyway, a diversity of approaches is definitely good. I'm glad you're up for continuing to support this plugin... let me know if I can be of help!

**Comment by antonioxdias** [comment]
@SamHall I see what the problem was. Trying to access the tiledImage before it being loaded. Just pushed a fix into [the same branch](https://github.com/antonioxdias/OpenSeadragonHTMLelements/tree/chore/use-tiled-image-coordinates), try it again!

**Comment by SamHall** [comment]
> @SamHall I see what the problem was. Trying to access the tiledImage before it being loaded. Just pushed a fix into [the same branch](https://github.com/antonioxdias/OpenSeadragonHTMLelements/tree/chore/use-tiled-image-coordinates), try it again!

Hooray! That did it. Thank you very much for the fix. 
You made my Monday!

Sam

**Comment by antonioxdias** [comment]
@SamHall Glad we could work this out! I won't include this changes in the core plugin, as they were quite over-fitted to your use case. But i'll keep them in mind if it ever comes the need to fully support a similar scenario.

**Comment by SMA-cgn** [comment]
Hi, I encountered the same issue. The plugin is great to easily add html elements. I am using many tiled images. Console is throwing the above mentioned error messages. I can suppress this. However, the position of the HTML overlay changes, when zooming in and out. 
Do you have any chance to enhance this great plugin to work with multiple images properly?

**Comment by antonioxdias** [comment]
Hey @SMA-cgn, can you try the [use-tiled-image-coordinates](https://github.com/antonioxdias/OpenSeadragonHTMLelements/tree/chore/use-tiled-image-coordinates) branch, mentioned above? If your use-case is similar to the original prompt of this issue, switching tiled images but keeping the overlay coordinates in sync, it might just work fine.

**Comment by SMA-cgn** [comment]
Hi, thanks a lot! 
I have a different use case. The branch does not fix it for me.
I tried https://github.com/openseadragon/html-overlay which works pretty well with multi images.

Thanks for your support!
